import { ResourceModel } from '../models/Resource';

export async function seedResources() {
  const resourcesData = [
    {
      title: `MDN Web Docs: JavaScript Functions Reference Guide`,
      type: 'OFFICIAL_DOC',
      provider: `Mozilla Developer Network`,
      canonicalUrl: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-SA 2.5',
      verificationStatus: 'VERIFIED',
      attribution: `Mozilla Contributors`,
      verificationEvidence: `Official Mozilla Foundation Developer Documentation`,
    },
    {
      title: `MDN Web Docs: Array Transformations & Higher-Order Functions`,
      type: 'OFFICIAL_DOC',
      provider: `Mozilla Developer Network`,
      canonicalUrl: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-SA 2.5',
      verificationStatus: 'VERIFIED',
      attribution: `Mozilla Contributors`,
      verificationEvidence: `Official Mozilla Foundation Developer Documentation`,
    },
    {
      title: `MDN Web Docs: JavaScript Event Loop & Concurrency`,
      type: 'OFFICIAL_DOC',
      provider: `Mozilla Developer Network`,
      canonicalUrl: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-SA 2.5',
      verificationStatus: 'VERIFIED',
      attribution: `Mozilla Contributors`,
      verificationEvidence: `Official Mozilla Foundation Developer Documentation`,
    },
    {
      title: `MDN Web Docs: HTML5 Semantic Elements & Structure`,
      type: 'OFFICIAL_DOC',
      provider: `Mozilla Developer Network`,
      canonicalUrl: 'https://developer.mozilla.org/en-US/docs/Glossary/Semantics',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-SA 2.5',
      verificationStatus: 'VERIFIED',
      attribution: `Mozilla Contributors`,
      verificationEvidence: `Official Mozilla Foundation Developer Documentation`,
    },
    {
      title: `MDN Web Docs: CSS Flexbox Layout Guide`,
      type: 'OFFICIAL_DOC',
      provider: `Mozilla Developer Network`,
      canonicalUrl: 'https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-SA 2.5',
      verificationStatus: 'VERIFIED',
      attribution: `Mozilla Contributors`,
      verificationEvidence: `Official Mozilla Foundation Developer Documentation`,
    },
    {
      title: `React.dev: Describing the UI & Component Trees`,
      type: 'OFFICIAL_DOC',
      provider: `React Core Team / Meta`,
      canonicalUrl: 'https://react.dev/learn/describing-the-ui',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-4.0',
      verificationStatus: 'VERIFIED',
      attribution: `React Core Team`,
      verificationEvidence: `Official React Documentation from react.dev`,
    },
    {
      title: `React.dev: Managing State & Effect Dependencies`,
      type: 'OFFICIAL_DOC',
      provider: `React Core Team / Meta`,
      canonicalUrl: 'https://react.dev/learn/managing-state',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-4.0',
      verificationStatus: 'VERIFIED',
      attribution: `React Core Team`,
      verificationEvidence: `Official React Documentation from react.dev`,
    },
    {
      title: `Next.js Documentation: App Router Architecture`,
      type: 'OFFICIAL_DOC',
      provider: `Vercel`,
      canonicalUrl: 'https://nextjs.org/docs/app',
      ownershipClass: 'OPEN_LICENSE',
      license: 'MIT',
      verificationStatus: 'VERIFIED',
      attribution: `Vercel / Next.js Team`,
      verificationEvidence: `Official Next.js Documentation from nextjs.org`,
    },
    {
      title: `Node.js Official Documentation: HTTP & Event Emitter Core`,
      type: 'OFFICIAL_DOC',
      provider: `OpenJS Foundation`,
      canonicalUrl: 'https://nodejs.org/docs/latest/api/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'MIT',
      verificationStatus: 'VERIFIED',
      attribution: `Node.js Contributors`,
      verificationEvidence: `Official Node.js Runtime Documentation`,
    },
    {
      title: `Express.js Guide: Middleware & Routing Patterns`,
      type: 'OFFICIAL_DOC',
      provider: `Express / OpenJS Foundation`,
      canonicalUrl: 'https://expressjs.com/en/guide/using-middleware.html',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-SA 3.0',
      verificationStatus: 'VERIFIED',
      attribution: `Express Contributors`,
      verificationEvidence: `Official Express.js Foundation Documentation`,
    },
    {
      title: `Python.org: The Python Tutorial & Standard Library`,
      type: 'OFFICIAL_DOC',
      provider: `Python Software Foundation`,
      canonicalUrl: 'https://docs.python.org/3/tutorial/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'PSF License',
      verificationStatus: 'VERIFIED',
      attribution: `Python Software Foundation`,
      verificationEvidence: `Official Python Documentation from python.org`,
    },
    {
      title: `Dev.java: Official Java Language Documentation & Tutorials`,
      type: 'OFFICIAL_DOC',
      provider: `Oracle Corporation`,
      canonicalUrl: 'https://dev.java/learn/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'Universal Permissive License',
      verificationStatus: 'VERIFIED',
      attribution: `Java Community / Oracle`,
      verificationEvidence: `Official Java Developer Portal Documentation`,
    },
    {
      title: `ISO C++ / cppreference: C++ Standard Library Reference`,
      type: 'OFFICIAL_DOC',
      provider: `cppreference.com`,
      canonicalUrl: 'https://en.cppreference.com/w/cpp',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-SA 3.0',
      verificationStatus: 'VERIFIED',
      attribution: `C++ Standards Committee Contributors`,
      verificationEvidence: `Community Standard C++ Reference Manual`,
    },
    {
      title: `Go.dev: Effective Go & Concurrency Patterns`,
      type: 'OFFICIAL_DOC',
      provider: `Google / Go Authors`,
      canonicalUrl: 'https://go.dev/doc/effective_go',
      ownershipClass: 'OPEN_LICENSE',
      license: 'BSD-3-Clause',
      verificationStatus: 'VERIFIED',
      attribution: `The Go Authors`,
      verificationEvidence: `Official Go Language Documentation`,
    },
    {
      title: `PostgreSQL Documentation: SQL Language Reference & Indexes`,
      type: 'OFFICIAL_DOC',
      provider: `PostgreSQL Global Development Group`,
      canonicalUrl: 'https://www.postgresql.org/docs/current/sql.html',
      ownershipClass: 'OPEN_LICENSE',
      license: 'PostgreSQL License',
      verificationStatus: 'VERIFIED',
      attribution: `PostgreSQL Contributors`,
      verificationEvidence: `Official PostgreSQL Relational Database Documentation`,
    },
    {
      title: `MongoDB Manual: Document Model, CRUD & Aggregation Pipeline`,
      type: 'OFFICIAL_DOC',
      provider: `MongoDB Inc.`,
      canonicalUrl: 'https://www.mongodb.com/docs/manual/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'SSPL / Documentation License',
      verificationStatus: 'VERIFIED',
      attribution: `MongoDB Documentation Team`,
      verificationEvidence: `Official MongoDB Database Documentation`,
    },
    {
      title: `Scikit-Learn User Guide: Supervised Learning & Preprocessing`,
      type: 'OFFICIAL_DOC',
      provider: `Scikit-Learn Developers`,
      canonicalUrl: 'https://scikit-learn.org/stable/user_guide.html',
      ownershipClass: 'OPEN_LICENSE',
      license: 'BSD-3-Clause',
      verificationStatus: 'VERIFIED',
      attribution: `Scikit-Learn Development Team`,
      verificationEvidence: `Official Scikit-Learn Machine Learning Documentation`,
    },
    {
      title: `PyTorch Tutorials: Deep Learning, Tensors & Autograd`,
      type: 'OFFICIAL_DOC',
      provider: `PyTorch / Linux Foundation`,
      canonicalUrl: 'https://pytorch.org/tutorials/beginner/basics/intro.html',
      ownershipClass: 'OPEN_LICENSE',
      license: 'BSD-3-Clause',
      verificationStatus: 'VERIFIED',
      attribution: `PyTorch Contributors`,
      verificationEvidence: `Official PyTorch Deep Learning Documentation`,
    },
    {
      title: `LangChain & OpenAI Guides: RAG Architecture & Tool Calling`,
      type: 'OFFICIAL_DOC',
      provider: `LangChain AI`,
      canonicalUrl: 'https://python.langchain.com/docs/tutorials/rag/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'MIT',
      verificationStatus: 'VERIFIED',
      attribution: `LangChain Community`,
      verificationEvidence: `Official LangChain Retrieval-Augmented Generation Documentation`,
    },
    {
      title: `Linux Documentation Project: Bash Guide for Beginners`,
      type: 'OFFICIAL_DOC',
      provider: `TLDP / Linux Community`,
      canonicalUrl: 'https://tldp.org/LDP/Bash-Beginners-Guide/html/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'GFDL',
      verificationStatus: 'VERIFIED',
      attribution: `Machtelt Garrels / TLDP`,
      verificationEvidence: `The Linux Documentation Project Public Manual`,
    },
    {
      title: `Git-SCM: Pro Git Book & Official Reference Manual`,
      type: 'OFFICIAL_DOC',
      provider: `Git Project`,
      canonicalUrl: 'https://git-scm.com/doc',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-NC-SA 3.0',
      verificationStatus: 'VERIFIED',
      attribution: `Scott Chacon & Ben Straub`,
      verificationEvidence: `Official Git Version Control Documentation`,
    },
    {
      title: `Docker Documentation: Container Architecture & Dockerfiles`,
      type: 'OFFICIAL_DOC',
      provider: `Docker Inc.`,
      canonicalUrl: 'https://docs.docker.com/get-started/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'Apache-2.0',
      verificationStatus: 'VERIFIED',
      attribution: `Docker Documentation Team`,
      verificationEvidence: `Official Docker Container Platform Documentation`,
    },
    {
      title: `Kubernetes Documentation: Pods, Services & Deployments`,
      type: 'OFFICIAL_DOC',
      provider: `Cloud Native Computing Foundation (CNCF)`,
      canonicalUrl: 'https://kubernetes.io/docs/concepts/',
      ownershipClass: 'OPEN_LICENSE',
      license: 'CC-BY-4.0',
      verificationStatus: 'VERIFIED',
      attribution: `Kubernetes Authors / CNCF`,
      verificationEvidence: `Official Kubernetes Container Orchestration Documentation`,
    },
    {
      title: `AWS Architecture Center: Cloud Well-Architected Framework`,
      type: 'OFFICIAL_DOC',
      provider: `Amazon Web Services`,
      canonicalUrl: 'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html',
      ownershipClass: 'OPEN_LICENSE',
      license: 'AWS Documentation License',
      verificationStatus: 'VERIFIED',
      attribution: `Amazon Web Services Architecture Team`,
      verificationEvidence: `Official AWS Cloud Architecture Guidance`,
    },
    {
      title: `React.js Complete Tutorial in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=emwAfCOog-s',
      embedUrl: 'https://www.youtube-nocookie.com/embed/emwAfCOog-s',
      externalId: 'emwAfCOog-s',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JSX and Virtual DOM in React JS in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=pGnZfsLnZLo',
      embedUrl: 'https://www.youtube-nocookie.com/embed/pGnZfsLnZLo',
      externalId: 'pGnZfsLnZLo',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Props and PropTypes in React JS in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=Ij_sNSRBOqY',
      embedUrl: 'https://www.youtube-nocookie.com/embed/Ij_sNSRBOqY',
      externalId: 'Ij_sNSRBOqY',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `useState Hook and State Batching in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=mT3l-jdxyA4',
      embedUrl: 'https://www.youtube-nocookie.com/embed/mT3l-jdxyA4',
      externalId: 'mT3l-jdxyA4',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `useEffect Hook Deep Dive in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=6Cr3uGirE7s',
      embedUrl: 'https://www.youtube-nocookie.com/embed/6Cr3uGirE7s',
      externalId: '6Cr3uGirE7s',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `React Custom Hooks and useReducer in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=MKJsUuSKA2I',
      embedUrl: 'https://www.youtube-nocookie.com/embed/MKJsUuSKA2I',
      externalId: 'MKJsUuSKA2I',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JavaScript Complete Foundations in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=dBUBYz75gdk',
      embedUrl: 'https://www.youtube-nocookie.com/embed/dBUBYz75gdk',
      externalId: 'dBUBYz75gdk',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JavaScript Array filter Method in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=EJngjEXbeHg',
      embedUrl: 'https://www.youtube-nocookie.com/embed/EJngjEXbeHg',
      externalId: 'EJngjEXbeHg',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JavaScript Array map Method in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=3dzD2ClzKio',
      embedUrl: 'https://www.youtube-nocookie.com/embed/3dzD2ClzKio',
      externalId: '3dzD2ClzKio',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JavaScript Array reduce Method in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=gpAA1jOfCaw',
      embedUrl: 'https://www.youtube-nocookie.com/embed/gpAA1jOfCaw',
      externalId: 'gpAA1jOfCaw',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JavaScript Optional Chaining and Nullish Coalescing in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=TGM3fulIHbg',
      embedUrl: 'https://www.youtube-nocookie.com/embed/TGM3fulIHbg',
      externalId: 'TGM3fulIHbg',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JavaScript Functions and Object Methods in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=ld0jn0WsfyU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/ld0jn0WsfyU',
      externalId: 'ld0jn0WsfyU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `JavaScript Call Apply and Bind in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=HBCm_dwcu9Q',
      embedUrl: 'https://www.youtube-nocookie.com/embed/HBCm_dwcu9Q',
      externalId: 'HBCm_dwcu9Q',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `The JavaScript Event Loop and Microtask Queue (Philip Roberts)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=8aGhZQkoFbQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/8aGhZQkoFbQ',
      externalId: '8aGhZQkoFbQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Philip Roberts / JSConf EU`,
      verificationEvidence: `Verified YouTube technical video resource from Philip Roberts / JSConf EU`,
    },
    {
      title: `HTML and CSS Web Development Intro in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=qlrLN_X5GXc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/qlrLN_X5GXc',
      externalId: 'qlrLN_X5GXc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Getting Started with HTML5 & VS Code in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=c7myDIKFjFg',
      embedUrl: 'https://www.youtube-nocookie.com/embed/c7myDIKFjFg',
      externalId: 'c7myDIKFjFg',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `HTML Typography and Text Hierarchy in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=6ukVlU9ScIs',
      embedUrl: 'https://www.youtube-nocookie.com/embed/6ukVlU9ScIs',
      externalId: '6ukVlU9ScIs',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `HTML Lists and Data Structuring in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=IeqkTS3fx60',
      embedUrl: 'https://www.youtube-nocookie.com/embed/IeqkTS3fx60',
      externalId: 'IeqkTS3fx60',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `HTML Hyperlinks and Document Anchors in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=e8wvygLG1ww',
      embedUrl: 'https://www.youtube-nocookie.com/embed/e8wvygLG1ww',
      externalId: 'e8wvygLG1ww',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `HTML Images and Multimedia in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=yGmiVqCAlsI',
      embedUrl: 'https://www.youtube-nocookie.com/embed/yGmiVqCAlsI',
      externalId: 'yGmiVqCAlsI',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `HTML Tables and Structured Grids in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=2RmKJAN8d_0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/2RmKJAN8d_0',
      externalId: '2RmKJAN8d_0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `HTML Forms and User Inputs in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=tDLLIq95VZU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/tDLLIq95VZU',
      externalId: 'tDLLIq95VZU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Node.js Complete Architecture in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=hiNqFhkyLgU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/hiNqFhkyLgU',
      externalId: 'hiNqFhkyLgU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Node.js CLI Arguments and HTTP Module in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=NXmjXkEckq4',
      embedUrl: 'https://www.youtube-nocookie.com/embed/NXmjXkEckq4',
      externalId: 'NXmjXkEckq4',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Node.js Module System CommonJS & ESM in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=IUtpkHpaXg0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/IUtpkHpaXg0',
      externalId: 'IUtpkHpaXg0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Express.js REST API and Middleware Architecture (Traversy Media)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=L72fhGm1tfE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/L72fhGm1tfE',
      externalId: 'L72fhGm1tfE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Traversy Media`,
      verificationEvidence: `Verified YouTube technical video resource from Traversy Media`,
    },
    {
      title: `Node.js JWT Authentication and Security Hardening (freeCodeCamp)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=mbsmsi7l3r4',
      embedUrl: 'https://www.youtube-nocookie.com/embed/mbsmsi7l3r4',
      externalId: 'mbsmsi7l3r4',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `freeCodeCamp.org`,
      verificationEvidence: `Verified YouTube technical video resource from freeCodeCamp.org`,
    },
    {
      title: `Node.js and Express Full Backend Course (freeCodeCamp)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/Oe421EPjeBE',
      externalId: 'Oe421EPjeBE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `freeCodeCamp.org`,
      verificationEvidence: `Verified YouTube technical video resource from freeCodeCamp.org`,
    },
    {
      title: `Next.js Introduction and Core Features in Tamil (Tech Tamil Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=6IC86VVQ0rQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/6IC86VVQ0rQ',
      externalId: '6IC86VVQ0rQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tech Tamil Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tech Tamil Tutorials`,
    },
    {
      title: `Next.js App Router Setup and Structure in Tamil (Tech Tamil Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=-wZ9i9Z2T4k',
      embedUrl: 'https://www.youtube-nocookie.com/embed/-wZ9i9Z2T4k',
      externalId: '-wZ9i9Z2T4k',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tech Tamil Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tech Tamil Tutorials`,
    },
    {
      title: `Next.js 15 File-System Routing in Tamil (Tech Tamil Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=89kPC0kG1IQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/89kPC0kG1IQ',
      externalId: '89kPC0kG1IQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tech Tamil Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tech Tamil Tutorials`,
    },
    {
      title: `Next.js Nested Routing and Layout Hierarchies in Tamil (Tech Tamil Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=6EJZJzrcl8A',
      embedUrl: 'https://www.youtube-nocookie.com/embed/6EJZJzrcl8A',
      externalId: '6EJZJzrcl8A',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tech Tamil Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tech Tamil Tutorials`,
    },
    {
      title: `Next.js 14 Full Course: Server Components & Actions (JavaScript Mastery)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=wm5gRf_rg74',
      embedUrl: 'https://www.youtube-nocookie.com/embed/wm5gRf_rg74',
      externalId: 'wm5gRf_rg74',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `JavaScript Mastery`,
      verificationEvidence: `Verified YouTube technical video resource from JavaScript Mastery`,
    },
    {
      title: `What is SQL and Database Design in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=QvTo1_-n0UE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/QvTo1_-n0UE',
      externalId: 'QvTo1_-n0UE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `SQL vs NoSQL Architecture Comparison in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=53eqvG3-1AM',
      embedUrl: 'https://www.youtube-nocookie.com/embed/53eqvG3-1AM',
      externalId: '53eqvG3-1AM',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `MySQL Database Setup and CLI in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=gsvYvufx1e0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/gsvYvufx1e0',
      externalId: 'gsvYvufx1e0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `SQL DDL Commands CREATE ALTER DROP in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=zHjpQnmA9sg',
      embedUrl: 'https://www.youtube-nocookie.com/embed/zHjpQnmA9sg',
      externalId: 'zHjpQnmA9sg',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `SQL DML Commands INSERT UPDATE DELETE in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=xPhImdnkJyo',
      embedUrl: 'https://www.youtube-nocookie.com/embed/xPhImdnkJyo',
      externalId: 'xPhImdnkJyo',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `SQL Practice Questions and Filtering in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=uhWu8JBRIa0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/uhWu8JBRIa0',
      externalId: 'uhWu8JBRIa0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `SQL Aggregate Functions COUNT SUM AVG in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=-FfEiNu2ar8',
      embedUrl: 'https://www.youtube-nocookie.com/embed/-FfEiNu2ar8',
      externalId: '-FfEiNu2ar8',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `SQL GROUP BY HAVING and ORDER BY in Tamil (Error Makes Clever)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=Y7Kqbc0sDGI',
      embedUrl: 'https://www.youtube-nocookie.com/embed/Y7Kqbc0sDGI',
      externalId: 'Y7Kqbc0sDGI',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Error Makes Clever`,
      verificationEvidence: `Verified YouTube technical video resource from Error Makes Clever`,
    },
    {
      title: `MongoDB Complete Tutorial in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=KD-2vh9v1co',
      embedUrl: 'https://www.youtube-nocookie.com/embed/KD-2vh9v1co',
      externalId: 'KD-2vh9v1co',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `MongoDB Queries on Embedded Documents in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=_H2IMUfFlXA',
      embedUrl: 'https://www.youtube-nocookie.com/embed/_H2IMUfFlXA',
      externalId: '_H2IMUfFlXA',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `MongoDB Array Queries and Operators in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=-xwqznF3NlE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/-xwqznF3NlE',
      externalId: '-xwqznF3NlE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `MongoDB Full Course for Beginners (freeCodeCamp)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=ofme2o29ngU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/ofme2o29ngU',
      externalId: 'ofme2o29ngU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `freeCodeCamp.org`,
      verificationEvidence: `Verified YouTube technical video resource from freeCodeCamp.org`,
    },
    {
      title: `Python Installation and Environment Setup in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=vSD3uBybnGc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/vSD3uBybnGc',
      externalId: 'vSD3uBybnGc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Python Variables and Memory References in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=6QQnpFAKHag',
      embedUrl: 'https://www.youtube-nocookie.com/embed/6QQnpFAKHag',
      externalId: '6QQnpFAKHag',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Python Online and Local Execution in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=yQwx6rCBvYk',
      embedUrl: 'https://www.youtube-nocookie.com/embed/yQwx6rCBvYk',
      externalId: 'yQwx6rCBvYk',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Python Visual Studio Code Development in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=vWz3zuSqJTo',
      embedUrl: 'https://www.youtube-nocookie.com/embed/vWz3zuSqJTo',
      externalId: 'vWz3zuSqJTo',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Python Keywords and Reserved Names in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=poXJ2J8QKMc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/poXJ2J8QKMc',
      externalId: 'poXJ2J8QKMc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Python User Input and Data Type Casting in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=391DB_ozvBs',
      embedUrl: 'https://www.youtube-nocookie.com/embed/391DB_ozvBs',
      externalId: '391DB_ozvBs',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Python SQLite Database Connectivity in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=RbU-WyuXw-o',
      embedUrl: 'https://www.youtube-nocookie.com/embed/RbU-WyuXw-o',
      externalId: 'RbU-WyuXw-o',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Python Complete Reference Course in Tamil (Tutor Joe's Stanley)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=TlUesRSESsY',
      embedUrl: 'https://www.youtube-nocookie.com/embed/TlUesRSESsY',
      externalId: 'TlUesRSESsY',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tutor Joe's Stanley`,
      verificationEvidence: `Verified YouTube technical video resource from Tutor Joe's Stanley`,
    },
    {
      title: `Introduction to Java and JVM Architecture in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=7yr81Dnn0NY',
      embedUrl: 'https://www.youtube-nocookie.com/embed/7yr81Dnn0NY',
      externalId: '7yr81Dnn0NY',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `First Java Program and Class Structure in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=jmHabsMagFc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/jmHabsMagFc',
      externalId: 'jmHabsMagFc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Java Variables and Primitive Data Types in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=lDQ8sEr_BqQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/lDQ8sEr_BqQ',
      externalId: 'lDQ8sEr_BqQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Java Comments and String Literals in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=OzalEN8n_SA',
      embedUrl: 'https://www.youtube-nocookie.com/embed/OzalEN8n_SA',
      externalId: 'OzalEN8n_SA',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Java Scanner and User Console Input in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=lwNfZE1d_oM',
      embedUrl: 'https://www.youtube-nocookie.com/embed/lwNfZE1d_oM',
      externalId: 'lwNfZE1d_oM',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Java Arithmetic and Assignment Operators in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=IyeSMcdM3KY',
      embedUrl: 'https://www.youtube-nocookie.com/embed/IyeSMcdM3KY',
      externalId: 'IyeSMcdM3KY',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Java Relational and Logical Operators in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=CiA29ckns44',
      embedUrl: 'https://www.youtube-nocookie.com/embed/CiA29ckns44',
      externalId: 'CiA29ckns44',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Java Bitwise Operators and Bit Shifting in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=8iuX_BoQL14',
      embedUrl: 'https://www.youtube-nocookie.com/embed/8iuX_BoQL14',
      externalId: '8iuX_BoQL14',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Introduction to C++ and Compilation in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=GbQlRSO6u9A',
      embedUrl: 'https://www.youtube-nocookie.com/embed/GbQlRSO6u9A',
      externalId: 'GbQlRSO6u9A',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `First C++ Program and Header Includes in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=n40TXFytqys',
      embedUrl: 'https://www.youtube-nocookie.com/embed/n40TXFytqys',
      externalId: 'n40TXFytqys',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `C++ Using Directive and Namespaces in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=sIlONEsaf4g',
      embedUrl: 'https://www.youtube-nocookie.com/embed/sIlONEsaf4g',
      externalId: 'sIlONEsaf4g',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `C++ Variables and Data Types in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=_K8w0JeNZ6E',
      embedUrl: 'https://www.youtube-nocookie.com/embed/_K8w0JeNZ6E',
      externalId: '_K8w0JeNZ6E',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `C++ Standard Output with Cout in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=a8cat181SQw',
      embedUrl: 'https://www.youtube-nocookie.com/embed/a8cat181SQw',
      externalId: 'a8cat181SQw',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `C++ Main Function and Return Status Codes in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=Ni4D3eVN6C0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/Ni4D3eVN6C0',
      externalId: 'Ni4D3eVN6C0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `C++ Standard Input with Cin in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=yUbx76dle7k',
      embedUrl: 'https://www.youtube-nocookie.com/embed/yUbx76dle7k',
      externalId: 'yUbx76dle7k',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `C++ Comments and Documentation Syntax in Tamil (Logic First Tamil)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=F_ArQwkD_sA',
      embedUrl: 'https://www.youtube-nocookie.com/embed/F_ArQwkD_sA',
      externalId: 'F_ArQwkD_sA',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Logic First Tamil`,
      verificationEvidence: `Verified YouTube technical video resource from Logic First Tamil`,
    },
    {
      title: `Golang Complete Course Introduction in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=jhwYKcRgy9w',
      embedUrl: 'https://www.youtube-nocookie.com/embed/jhwYKcRgy9w',
      externalId: 'jhwYKcRgy9w',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `Golang Hello World and Tooling in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=crHNttwMhuQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/crHNttwMhuQ',
      externalId: 'crHNttwMhuQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `Golang Package Main and Imports in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=NJpVUagoe0M',
      embedUrl: 'https://www.youtube-nocookie.com/embed/NJpVUagoe0M',
      externalId: 'NJpVUagoe0M',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `Golang Variables and Short Declaration in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=o4izbVaF6k8',
      embedUrl: 'https://www.youtube-nocookie.com/embed/o4izbVaF6k8',
      externalId: 'o4izbVaF6k8',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `Golang Constants and Type Inference in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=tQjs4M9Akns',
      embedUrl: 'https://www.youtube-nocookie.com/embed/tQjs4M9Akns',
      externalId: 'tQjs4M9Akns',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `Golang Data Types and Slices in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=3usdrzwQ48o',
      embedUrl: 'https://www.youtube-nocookie.com/embed/3usdrzwQ48o',
      externalId: '3usdrzwQ48o',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `Golang User Input and Formatting in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=yMSlLC_rsBo',
      embedUrl: 'https://www.youtube-nocookie.com/embed/yMSlLC_rsBo',
      externalId: 'yMSlLC_rsBo',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `Golang Functions and Multiple Return Values in Tamil (T's Tech)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=zLayHZImGqY',
      embedUrl: 'https://www.youtube-nocookie.com/embed/zLayHZImGqY',
      externalId: 'zLayHZImGqY',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `T's Tech`,
      verificationEvidence: `Verified YouTube technical video resource from T's Tech`,
    },
    {
      title: `What is Linux Kernel and User Space in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=-3zlmLkT52s',
      embedUrl: 'https://www.youtube-nocookie.com/embed/-3zlmLkT52s',
      externalId: '-3zlmLkT52s',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Linux Shell Explained for Beginners in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=Alpjl5WqgW8',
      embedUrl: 'https://www.youtube-nocookie.com/embed/Alpjl5WqgW8',
      externalId: 'Alpjl5WqgW8',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Top Essential Linux Commands for DevOps in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=sVkUaSlvNzc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/sVkUaSlvNzc',
      externalId: 'sVkUaSlvNzc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Linux File Editing with Echo, Nano and Vim in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=A9KbndGZhBU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/A9KbndGZhBU',
      externalId: 'A9KbndGZhBU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Bash Shell Scripting for Beginners in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=aCwGPaEbYFA',
      embedUrl: 'https://www.youtube-nocookie.com/embed/aCwGPaEbYFA',
      externalId: 'aCwGPaEbYFA',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Linux Shell Variables and Environment Export in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=4ew35eroL7M',
      embedUrl: 'https://www.youtube-nocookie.com/embed/4ew35eroL7M',
      externalId: '4ew35eroL7M',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Git & GitHub Introduction for Beginners in Tamil (Tamil Tech Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=QALpfsvcS6I',
      embedUrl: 'https://www.youtube-nocookie.com/embed/QALpfsvcS6I',
      externalId: 'QALpfsvcS6I',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tamil Tech Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tamil Tech Tutorials`,
    },
    {
      title: `Master Git Basics in Minutes in Tamil (Tamil Tech Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=fwOATnzBGco',
      embedUrl: 'https://www.youtube-nocookie.com/embed/fwOATnzBGco',
      externalId: 'fwOATnzBGco',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tamil Tech Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tamil Tech Tutorials`,
    },
    {
      title: `Essential Git Commands and Log in Tamil (Tamil Tech Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=qBpA0aZSsvM',
      embedUrl: 'https://www.youtube-nocookie.com/embed/qBpA0aZSsvM',
      externalId: 'qBpA0aZSsvM',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tamil Tech Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tamil Tech Tutorials`,
    },
    {
      title: `Git Branching and Merging Techniques in Tamil (Tamil Tech Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=ABGtj-ny0XM',
      embedUrl: 'https://www.youtube-nocookie.com/embed/ABGtj-ny0XM',
      externalId: 'ABGtj-ny0XM',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tamil Tech Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tamil Tech Tutorials`,
    },
    {
      title: `GitHub Basics and Remote Repositories in Tamil (Tamil Tech Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=VlZfqdDDwbE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/VlZfqdDDwbE',
      externalId: 'VlZfqdDDwbE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tamil Tech Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tamil Tech Tutorials`,
    },
    {
      title: `Practical Git & GitHub Hands-On Guide in Tamil (Tamil Tech Tutorials)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=tbjxyc0IBOQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/tbjxyc0IBOQ',
      externalId: 'tbjxyc0IBOQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Tamil Tech Tutorials`,
      verificationEvidence: `Verified YouTube technical video resource from Tamil Tech Tutorials`,
    },
    {
      title: `Docker Tutorial for Beginners in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=9_QAItNHRzU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/9_QAItNHRzU',
      externalId: '9_QAItNHRzU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `What is a Docker Container vs Virtual Machine in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=p0uIsdBzcYs',
      embedUrl: 'https://www.youtube-nocookie.com/embed/p0uIsdBzcYs',
      externalId: 'p0uIsdBzcYs',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Docker Basic Commands and Lifecycle in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=nvXhambtoN0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/nvXhambtoN0',
      externalId: 'nvXhambtoN0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Docker Port Mapping and Networking in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=frCX9nslvlo',
      embedUrl: 'https://www.youtube-nocookie.com/embed/frCX9nslvlo',
      externalId: 'frCX9nslvlo',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Docker Volumes and Data Persistence in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=bfnnneQqQpQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/bfnnneQqQpQ',
      externalId: 'bfnnneQqQpQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Docker Bind Mounts vs Named Volumes in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=F2g8roac884',
      embedUrl: 'https://www.youtube-nocookie.com/embed/F2g8roac884',
      externalId: 'F2g8roac884',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Dockerfile Creation and Best Practices in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=U4KKITaFi4Y',
      embedUrl: 'https://www.youtube-nocookie.com/embed/U4KKITaFi4Y',
      externalId: 'U4KKITaFi4Y',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Docker Hands-On Guide from Dockerfile to Hub in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=i8vnIi08UxQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/i8vnIi08UxQ',
      externalId: 'i8vnIi08UxQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes Explained in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=8c4oEuANkTQ',
      embedUrl: 'https://www.youtube-nocookie.com/embed/8c4oEuANkTQ',
      externalId: '8c4oEuANkTQ',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes Architecture and Control Plane in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=aiUrjgJjLOw',
      embedUrl: 'https://www.youtube-nocookie.com/embed/aiUrjgJjLOw',
      externalId: 'aiUrjgJjLOw',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes Pods and Containers Explained in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=DB7bkdzrxqU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/DB7bkdzrxqU',
      externalId: 'DB7bkdzrxqU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes ReplicaSets and Desired State in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=PiinMukq8uw',
      embedUrl: 'https://www.youtube-nocookie.com/embed/PiinMukq8uw',
      externalId: 'PiinMukq8uw',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes Cluster Node and Pod Hierarchy in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=fjnAj_HESa4',
      embedUrl: 'https://www.youtube-nocookie.com/embed/fjnAj_HESa4',
      externalId: 'fjnAj_HESa4',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes Services and Endpoints Networking in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=rIKaESMkeRE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/rIKaESMkeRE',
      externalId: 'rIKaESMkeRE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes Service Types ClusterIP NodePort LoadBalancer in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=Yqsa6oHS_c0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/Yqsa6oHS_c0',
      externalId: 'Yqsa6oHS_c0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Kubernetes Deployments and Rolling Updates in Tamil (Simply Byte)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=eLa_YB_Witc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/eLa_YB_Witc',
      externalId: 'eLa_YB_Witc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Simply Byte`,
      verificationEvidence: `Verified YouTube technical video resource from Simply Byte`,
    },
    {
      title: `Machine Learning Foundations in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=aiCIWGSCCKo',
      embedUrl: 'https://www.youtube-nocookie.com/embed/aiCIWGSCCKo',
      externalId: 'aiCIWGSCCKo',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Linear Regression and Logistic Regression in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=2dHflWd_5uE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/2dHflWd_5uE',
      externalId: '2dHflWd_5uE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Decision Trees Classifier Algorithm in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=WTjK0OUr9us',
      embedUrl: 'https://www.youtube-nocookie.com/embed/WTjK0OUr9us',
      externalId: 'WTjK0OUr9us',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `K-Nearest Neighbors Algorithm in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=wtTqeP6ZkO0',
      embedUrl: 'https://www.youtube-nocookie.com/embed/wtTqeP6ZkO0',
      externalId: 'wtTqeP6ZkO0',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Underfitting and Overfitting Bias-Variance in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=8rH3c2ClPms',
      embedUrl: 'https://www.youtube-nocookie.com/embed/8rH3c2ClPms',
      externalId: '8rH3c2ClPms',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Random Forest Ensemble Classifier in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=fxE4nlU4UjI',
      embedUrl: 'https://www.youtube-nocookie.com/embed/fxE4nlU4UjI',
      externalId: 'fxE4nlU4UjI',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Support Vector Machines SVM in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=cCpCjPI7Bnc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/cCpCjPI7Bnc',
      externalId: 'cCpCjPI7Bnc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Naive Bayes Classification Algorithm in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=oxSsvWISu0w',
      embedUrl: 'https://www.youtube-nocookie.com/embed/oxSsvWISu0w',
      externalId: 'oxSsvWISu0w',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Deep Learning and Artificial Neural Networks in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=8t_AJicjR-w',
      embedUrl: 'https://www.youtube-nocookie.com/embed/8t_AJicjR-w',
      externalId: '8t_AJicjR-w',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Training a Neural Network and Loss Functions in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=db4v2fYgfzM',
      embedUrl: 'https://www.youtube-nocookie.com/embed/db4v2fYgfzM',
      externalId: 'db4v2fYgfzM',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Neural Network Activation Functions ReLU Sigmoid in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=AH5DepaIKZo',
      embedUrl: 'https://www.youtube-nocookie.com/embed/AH5DepaIKZo',
      externalId: 'AH5DepaIKZo',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Multilayer Perceptrons and Hidden Representations in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=QIj-UlDrePY',
      embedUrl: 'https://www.youtube-nocookie.com/embed/QIj-UlDrePY',
      externalId: 'QIj-UlDrePY',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Chain Rule and Backpropagation Mechanics in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=uiW4seCxYXw',
      embedUrl: 'https://www.youtube-nocookie.com/embed/uiW4seCxYXw',
      externalId: 'uiW4seCxYXw',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Vanishing and Exploding Gradient Problem in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=WV0-dGSJjRE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/WV0-dGSJjRE',
      externalId: 'WV0-dGSJjRE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Dropout Layers and Neural Network Regularization in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=zmEF3CfK6qU',
      embedUrl: 'https://www.youtube-nocookie.com/embed/zmEF3CfK6qU',
      externalId: 'zmEF3CfK6qU',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `Adam Optimizer and Adaptive Learning Rates in Tamil (TAMIL CODE)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=hLbmOlmQBS4',
      embedUrl: 'https://www.youtube-nocookie.com/embed/hLbmOlmQBS4',
      externalId: 'hLbmOlmQBS4',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TAMIL CODE`,
      verificationEvidence: `Verified YouTube technical video resource from TAMIL CODE`,
    },
    {
      title: `State of GPT and Large Language Model Foundations (Andrej Karpathy)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=zjkBMFhNj_g',
      embedUrl: 'https://www.youtube-nocookie.com/embed/zjkBMFhNj_g',
      externalId: 'zjkBMFhNj_g',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `Andrej Karpathy`,
      verificationEvidence: `Verified YouTube technical video resource from Andrej Karpathy`,
    },
    {
      title: `Prompt Engineering and In-Context Reasoning for LLMs (freeCodeCamp)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=_ZvnD93Mr5r',
      embedUrl: 'https://www.youtube-nocookie.com/embed/_ZvnD93Mr5r',
      externalId: '_ZvnD93Mr5r',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `freeCodeCamp.org`,
      verificationEvidence: `Verified YouTube technical video resource from freeCodeCamp.org`,
    },
    {
      title: `Embeddings and Vector Search Architecture (StatQuest)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=viZrOnJclYg',
      embedUrl: 'https://www.youtube-nocookie.com/embed/viZrOnJclYg',
      externalId: 'viZrOnJclYg',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `StatQuest with Josh Starmer`,
      verificationEvidence: `Verified YouTube technical video resource from StatQuest with Josh Starmer`,
    },
    {
      title: `Retrieval-Augmented Generation RAG Architecture (freeCodeCamp)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=T-D1OfcDW1M',
      embedUrl: 'https://www.youtube-nocookie.com/embed/T-D1OfcDW1M',
      externalId: 'T-D1OfcDW1M',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `freeCodeCamp.org`,
      verificationEvidence: `Verified YouTube technical video resource from freeCodeCamp.org`,
    },
    {
      title: `Fine-Tuning LLMs with LoRA and Parameter Efficient Adapters (freeCodeCamp)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=eC6Hd1hFvos',
      embedUrl: 'https://www.youtube-nocookie.com/embed/eC6Hd1hFvos',
      externalId: 'eC6Hd1hFvos',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `freeCodeCamp.org`,
      verificationEvidence: `Verified YouTube technical video resource from freeCodeCamp.org`,
    },
    {
      title: `Autonomous AI Agents and Tool Calling with LangChain (LangChain AI)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=DWbegjA7sI4',
      embedUrl: 'https://www.youtube-nocookie.com/embed/DWbegjA7sI4',
      externalId: 'DWbegjA7sI4',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `LangChain AI`,
      verificationEvidence: `Verified YouTube technical video resource from LangChain AI`,
    },
    {
      title: `AWS Cloud Computing Fundamentals and IAM (TechWorld with Nana)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=3hLmDS179YE',
      embedUrl: 'https://www.youtube-nocookie.com/embed/3hLmDS179YE',
      externalId: '3hLmDS179YE',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TechWorld with Nana`,
      verificationEvidence: `Verified YouTube technical video resource from TechWorld with Nana`,
    },
    {
      title: `AWS EC2 Virtual Servers and Security Groups (TechWorld with Nana)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=ulprqHHWlng',
      embedUrl: 'https://www.youtube-nocookie.com/embed/ulprqHHWlng',
      externalId: 'ulprqHHWlng',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TechWorld with Nana`,
      verificationEvidence: `Verified YouTube technical video resource from TechWorld with Nana`,
    },
    {
      title: `AWS S3 Object Storage and Bucket Policies (TechWorld with Nana)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=7m_q1ldzw0U',
      embedUrl: 'https://www.youtube-nocookie.com/embed/7m_q1ldzw0U',
      externalId: '7m_q1ldzw0U',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TechWorld with Nana`,
      verificationEvidence: `Verified YouTube technical video resource from TechWorld with Nana`,
    },
    {
      title: `AWS VPC Networking and Subnets Architecture (TechWorld with Nana)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=g2JOHLHh4rI',
      embedUrl: 'https://www.youtube-nocookie.com/embed/g2JOHLHh4rI',
      externalId: 'g2JOHLHh4rI',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TechWorld with Nana`,
      verificationEvidence: `Verified YouTube technical video resource from TechWorld with Nana`,
    },
    {
      title: `AWS RDS Managed Relational Databases (freeCodeCamp)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=SOTamWNgDKc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/SOTamWNgDKc',
      externalId: 'SOTamWNgDKc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `freeCodeCamp.org`,
      verificationEvidence: `Verified YouTube technical video resource from freeCodeCamp.org`,
    },
    {
      title: `AWS Lambda Serverless Functions and Event Architecture (TechWorld with Nana)`,
      type: 'VIDEO',
      provider: 'YouTube',
      canonicalUrl: 'https://www.youtube.com/watch?v=EBSdyoO3goc',
      embedUrl: 'https://www.youtube-nocookie.com/embed/EBSdyoO3goc',
      externalId: 'EBSdyoO3goc',
      ownershipClass: 'EMBEDDED',
      license: 'Standard YouTube License (Embed Allowed by Creator)',
      verificationStatus: 'VERIFIED',
      attribution: `TechWorld with Nana`,
      verificationEvidence: `Verified YouTube technical video resource from TechWorld with Nana`,
    },
  ];

  const created = await ResourceModel.create(resourcesData);
  const resourceMap = new Map<string, any>();
  created.forEach((r) => {
    resourceMap.set(r.title, r);
  });
  return resourceMap;
}
